# Basics Of Numpy

Numpy is the fundamental package for scientific computing with Python. It contains among other things:

1. A powerful N-dimensional array object

2. Sophisticated functionss

3. Tools for integrating C/C++ and Fortan code

4. Useful linear algebra, Fourier Transform and random number capabilities.

### Difference betweeen list and numpy

1. Numpy is faster than list because  an integer in numpy is by default cached into 4 bytes (i.e., Int32) memory space and it can be explicitly specified to store in 2 bytes(i.e., Int16) or even in a 1 byte (i.e.,Int8) whereas in lists  there is a lot more information to store along with each integer they  are Size, Refrence Count, Object Type and Object value which inturn will have there values which requires memory of 8 bytes of memory except size which requires 2 bytes of memory. Therefore as numpy uses less amount of memory  which can be read fastly it is faster than lists.

2. As datatype should be same of all the elements in numpy array there is no type checking when iterating through objects  which makes it faster than lists.

3. Numpy uses contiguous memory 



### Source: https://numpy.org/

### Installing Numpy 

!pip3 install numpy

In [1]:
# Importing the Numpy library
import numpy as np

In [2]:
# Check version of the numpy library
np.__version__

'1.18.1'

In [3]:
# Create a numpy array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
[1,4,'2',5,False]

[1, 4, '2', 5, False]

In [5]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of all the elements
np.array([1,4,2,'5',3,False])

array(['1', '4', '2', '5', '3', 'False'], dtype='<U11')

In [6]:
# If we add an element of Boolean data type in a numpy array
# then it will upcast the data type to int of all the elements.
np.array([1,2,4,False])

array([1, 2, 4, 0])

In [7]:
# Let's  create a list and multiply it by 2 and see how the computation works
sample_list = [1,2,3,4] # expected output after multiplying with 2 is [2,4,6,8]
print(sample_list * 2) # but the elements in the list repeats 2 times

[1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
# Let's check the same with numpy array
sample_numpy_array = np.array([1,2,3,4])
print(sample_numpy_array * 2)

[2 4 6 8]


In [9]:
# Create a matrix using list

matrix_list = [[1,2,3],
         [4,5,6],
         [7,8,9]]

In [10]:
matrix_list # It doesnt create a matrix infact its a nested list 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
type(matrix_list)

list

In [12]:
# Create a matrix using numpy
matrix = [[1,2,3],
         [4,5,6],
         [7,8,9]]
matrix_numpy = np.array(matrix) # creates a 3 x 3 matrix
matrix_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Elements can be accesed using index
matrix_numpy[0][1] # we are accessing 0 th element i.e., [1,2,3] and 1st elemnt in it i.e., 2

2

In [14]:
# Create a 3 x 3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[7, 0, 2],
       [1, 9, 8],
       [3, 5, 9]])

In [15]:
# Create another matrix
np.random.randint(0,10,(3,3))

array([[8, 4, 6],
       [7, 8, 9],
       [4, 6, 2]])

In [16]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [17]:
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [18]:
# Create a matrix of zeros of specific dimensions
# create a 4 x 5 integer array filled with zeros
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
# create 2 x 10 integer array filled wiith ones
np.ones((2,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
# create an identity matrix
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
# create a matrix filled with any specific number of specific dimension
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])